title = "Cray System Management (CSM)"
theme = "hugo-theme-learn"
baseURL = "/docs-csm/"
languageCode = "en-US"
defaultContentLanguage = "en-10"
defaultContentLanguageInSubdir = true
showVisitedLinks = true
refLinksErrorLevel = "WARNING"

[outputs]
home = ["HTML", "RSS", "JSON" ]

[params]
shortTitle = "Cray System Management"
themeVariant = "blue"
disableNextPrev = true
disableLandingPageButton = true

[languages]
  [languages.en-09]
    contentDir = "content/0.9"
    languageName = "0.9"
    weight = 10
    landingPageURL = "/docs-csm/en-09"
    # Support for raw html for <a name=""> anchor links
    [markup.goldmark.renderer]
    unsafe= true
  [languages.en-10]
    contentDir = "content/1.0"
    languageName = "1.0"
    weight = 20
    landingPageURL = "/docs-csm/en-10"
  #[languages.en-11]
  #  contentDir = "content/1.1"
  #  languageName = "1.1"
  #  weight = 30
  #  landingPageURL = "/docs-csm/en-11"
  [languages.en-12]
    contentDir = "content/1.2"
    languageName = "1.2"
    weight = 40
    landingPageURL = "/docs-csm/en-12"
  [languages.en-13]
    contentDir = "content/1.3"
    languageName = "1.3"
    weight = 40
    landingPageURL = "/docs-csm/en-13"
