version: '3'

services:
  hugo_serve:
    container_name: hugo_serve
    # image: peaceiris/hugo:v0.x.x
    image: peaceiris/hugo:v0.84.4-mod   # Hugo Modules
    # image: peaceiris/hugo:v0.x.x-full  # Hugo Modules and Node.js
    ports:
      - "1313:1313"
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
  hugo_prep:
    container_name: hugo_prep
    image: ubuntu
    volumes:
      - ${PWD}:/src
    command:
      - /src/bin/convert-docs-to-hugo.sh
      - --source
      - /src/docs-csm/
      - --destination
      - /src/content